apiVersion: apps/v1
kind: Deployment
metadata:
  name: micropay-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micropay-db
  template:
    metadata:
      labels:
        app: micropay-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: security_db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: security-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SPRING_DATASOURCE_PASSWORD
