apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: micropay-db

spec:
  serviceName: micropay-db
  replicas: 2
  selector:
    matchLabels:
      app: micropay-db
  template:
    metadata:
      labels:
        app: micropay-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: micropay-db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_USERNAME
                  name: security-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SPRING_DATASOURCE_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
