apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - name: security-service
          image: docker.io/dockerforomar/micropay-security:latest
          ports:
            - containerPort: 8150
          envFrom:
            - configMapRef:
                name: db-config
            - configMapRef:
                name: db-secret
          env:
            - name: SECURITY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: security-secret
                  key: jwt-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8150
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8150
            initialDelaySeconds: 30
            periodSeconds: 10
